spring:
  application:
    name: dispatcher

dispatcher:
  request-service-url: http://localhost:8082
  mechanic-service-url: http://localhost:8081
  auth-enabled: true
  api-key-header-name: X-Api-Key
