spring.application.name=mechanic
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/mechanic
spring.data.mongodb.auto-index-creation=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
