spring.application.name=request
server.port=8082
spring.data.mongodb.uri=mongodb://localhost:27017/smart_road_assist_request
spring.data.mongodb.auto-index-creation=true
dispatcher.enforce-internal-header=true
dispatcher.internal-header-name=X-Dispatcher-Secret
dispatcher.shared-secret=smart-road-assist-internal-secret
